### ISSUE TITLE
Pressing the enter key does not show the result

### ISSUE THREAD

**Issue by tareq2** [sunnygoyal/scienfic-calculator#6]
When pressing the enter key to show the result the menu containing the calculator hides and so we cannot get the result.
OS:windows 10 
Firefox:40.0.3
calculator :5.3.6.1-signed

**Comment by Ede123** [comment]
Can you check with a clean profile (use the [Profile Manager](https://support.mozilla.org/en-US/kb/profile-manager-create-and-remove-firefox-profiles) to create a new temporary profile) if the problem persists and is not caused by any other add-on?

I don't have access to a Windows 10 machine, so I can't test it myself right now. On Windows 7 everything is working fine, though.

**Comment by tareq2** [comment]
With a clean profile it is working.
But with the old one it is not working although i have disabled all other add-ons.

**Comment by Ede123** [comment]
Can you find out what the enter key is actually triggering in you old profile?
I assume it executes some other function (independent of Scientific Calculator) which causes the menu to loose focus (therefore it closes).

**Comment by tareq2** [comment]
I also noticed that the click on the calculator icon doesn't show the menu

**Comment by Ede123** [comment]
In your productive profile or the clean one?

It's working as expected for me (on Windows 7)

**Comment by tareq2** [comment]
I meant on the productive profile.
Thank you for your time and for this nice calculator.
