### ISSUE TITLE
Mark the base number on icon

### ISSUE THREAD

**Issue by yfdyh000** [sunnygoyal/scienfic-calculator#7]
Users may forget the base has been modified, and get a strange results.
For a custom base, it can be marked as C.

**Comment by Ede123** [comment]
Good idea! Happened to myself, too, at various occasions.

**Comment by Ede123** [comment]
Fixed in abf2cc2b8184281a9d595dc66bf7e8f6c4703169.

You can download a development snapshot [here](https://github.com/sunnygoyal/scienfic-calculator/releases/download/dev/scicalc.xpi).

Should this be optional (i.e. should I add a preference for it in options)? I already hide the base for base 10, so most people won't see it almost all the time anyway...
Other suggestions are of course welcome, too.

**Comment by yfdyh000** [comment]
There are some gaps with my expected, but not bad.

I prefer like this: ![uBlock badge](https://cloud.githubusercontent.com/assets/1769875/10417606/8b02c52c-7074-11e5-8300-abb07ab0b73b.png)
https://developer.mozilla.org/en-US/Add-ons/SDK/Low-Level_APIs/ui_button_action#Badged_buttons

**Comment by Ede123** [comment]
I'll think about it, but I actually like it the way it looks now.

Your suggested design would need a considerable amount of additional code (that might break on updates) and I don't see any real benefit (the additional horizontal space is negligible in my opinion).

Please note that I cannot use the "badged button" you linked to, since Scientific Calculator does not make use of the add-on SDK.

**Comment by yfdyh000** [comment]
En, I understand, just an idea, whether it will better if not take up space on the corner. or, a background or border.
