### ISSUE TITLE
Stoped to expand on Mac

### ISSUE THREAD

**Issue by esstein** [sunnygoyal/scienfic-calculator#9]
I can see the tool bar icon but it stopped expand when I click on calc icon. It occurs some versions ago, now I'm using ff 45.0.2.

**Comment by Ede123** [comment]
Could you verify you're using the latest version of Scientific Calculator?
Also could you please check if the issue persists with a clean profile (you can simply [add a new profile](https://support.mozilla.org/en-US/kb/profile-manager-create-and-remove-firefox-profiles) for this test and continue to use your current profile afterwards).

If the issue is still reproducible then please open the browser console (preferably in the clean profile) and check if there are logged any errors on startup and when trying to expand the calculator and copy/paste them here.

**Comment by Ede123** [comment]
Closing for now due to lack of response... Feel free to re-open if you're still experiencing this problem and can provide the necessary information to investigate the issue.
